
name: random_picker
description: A playful Random Picker app for Android and iOS (and Web for demo).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.4.4
  firebase_analytics: ^11.2.1

  # Maps & Location
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1

  # Ads
  google_mobile_ads: ^5.1.0
  applovin_max: ^3.10.2

  # Sharing & Screenshot
  share_plus: ^10.0.2
  screenshot: ^3.0.0
  path_provider: ^2.1.4

  # UI & utils
  intl: ^0.20.2   # <-- อัปเป็น 0.20.2
  uuid: ^4.4.2
  lottie: ^3.1.3
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  generate: true
